### ISSUE TITLE
Shebang line "#!/usr/bin/env node" trouble

### ISSUE THREAD

**Issue by hartwork** [arikon/npm2debian#23]
In Debian sid, `node` is called `nodejs` instead, see:

```
$ npm2debian 
/usr/bin/env: node: No such file or directory

$ nodejs /usr/local/bin/npm2debian 
Missing required argument:
  PKG : Package (required)
```

My guess is that it's the case because `/usr/sbin/node` is taken by Amateur Packet Radio Node program already (see https://packages.debian.org/wheezy/all/node/filelist).

Please update the shebang line accordingly.

**Comment by arikon** [comment]
A wrapper is a good idea

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
